# Generated by Django 2.0.4 on 2018-06-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('upload_time', models.DateTimeField(null=True)),
                ('print_start_time', models.DateTimeField(null=True)),
                ('print_end_time', models.DateTimeField(null=True)),
                ('printer_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('quota', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InnovationHubWebsite.User'),
        ),
    ]
