# Generated by Django 2.0.4 on 2018-06-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0002_auto_20180622_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPrints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('fk_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InnovationHubWebsite.Job')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InnovationHubWebsite.User')),
            ],
        ),
        migrations.CreateModel(
            name='RecentPrints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InnovationHubWebsite.Job')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InnovationHubWebsite.User')),
            ],
        ),
    ]
