# Generated by Django 2.0.4 on 2018-06-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0004_auto_20180626_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredprint',
            name='fk_user',
        ),
        migrations.RemoveField(
            model_name='recentprint',
            name='fk_user',
        ),
    ]
