# Generated by Django 2.0.4 on 2018-07-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0005_auto_20180629_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='fk_user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
