# Generated by Django 2.0.4 on 2018-07-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0007_auto_20180727_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
