# Generated by Django 2.0.4 on 2018-08-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0009_job_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='special_marker',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
