# Generated by Django 2.0.4 on 2018-08-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0011_auto_20180824_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file_path_obj',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='file_path_stl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=500),
        ),
    ]
