# Generated by Django 2.0.4 on 2018-09-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0012_auto_20180831_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
