# Generated by Django 2.0.4 on 2018-11-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0014_profile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='print_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
