# Generated by Django 2.0.4 on 2018-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0015_job_print_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredprint',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='featuredprint',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='featuredprint',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
