# Generated by Django 2.0.4 on 2018-12-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0016_auto_20181117_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredprint',
            name='votes',
        ),
    ]
