# Generated by Django 2.0.4 on 2018-12-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0018_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='active_users_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_users_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='very_active_users_num',
            field=models.IntegerField(null=True),
        ),
    ]
