# Generated by Django 2.0.4 on 2018-12-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0019_auto_20181219_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='print_time_average',
            new_name='print_time',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='wait_time_average',
            new_name='wait_time',
        ),
    ]
