# Generated by Django 2.0.4 on 2018-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0020_auto_20181219_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='wait_time',
            field=models.IntegerField(null=True),
        ),
    ]
