# Generated by Django 2.0.4 on 2018-12-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnovationHubWebsite', '0021_job_wait_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
